# 构建 VitePress 站点并将其部署到 GitHub Pages 的示例工作流程
#
name: Deploy VitePress site to Pages

on:
    # 在针对 `main` 分支的推送上运行。如果你
    # 使用 `master` 分支作为默认分支，请将其更改为 `master`
    push:
        branches: [ main ]

    # 允许你从 Actions 选项卡手动运行此工作流程
    workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限，以允许部署到 GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write

# 只允许同时进行一次部署，跳过正在运行和最新队列之间的运行队列
# 但是，不要取消正在进行的运行，因为我们希望允许这些生产部署完成
concurrency:
    group: pages
    cancel-in-progress: false

jobs:
    # 构建工作
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v5
                with:
                    fetch-depth: 0 # 如果未启用 lastUpdated，则不需要
            # - uses: pnpm/action-setup@v4 # 如果使用 pnpm，请取消此区域注释
            #   with:
            #     version: 9
            # - uses: oven-sh/setup-bun@v1 # 如果使用 Bun，请取消注释
            -   name: Setup Node
                uses: actions/setup-node@v6
                with:
                    node-version: 24
                    cache: npm # 或 pnpm / yarn
            -   name: Setup Pages
                uses: actions/configure-pages@v4 # 在工作流程自动配置GithubPages
            -   name: Install dependencies
                run: npm ci # 或 pnpm install / yarn install / bun install  # 安装依赖
            -   name: Build with VitePress
                run: |
                    npm run docs:build # 启动项目
                    touch .nojekyll  # 通知githubpages不要使用Jekyll处理这个站点，不知道为啥不生效，就手动搞了
            -   name: Upload artifact
                uses: actions/upload-pages-artifact@v3 # 上传构建产物
                with:
                    path: docs/.vitepress/dist # 指定上传的路径，当前是根目录，如果是docs需要加docs/的前缀

    # 部署工作
    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        needs: build        # 在build后面完成
        runs-on: ubuntu-latest  # 运行在最新版本的ubuntu系统上
        name: Deploy
        steps:
            -   name: Deploy to GitHub Pages
                id: deployment  # 指定id
                uses: actions/deploy-pages@v4  # 将之前的构建产物部署到github pages中
